# Generated by Django 2.2.1 on 2019-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIGUN_CD', models.CharField(max_length=255, verbose_name='시군코드')),
                ('SIGUN_NM', models.CharField(max_length=255, verbose_name='시군명')),
                ('BIZPLC_NM', models.CharField(max_length=255, verbose_name='사업장명')),
                ('LICENSG_DE', models.DateField(verbose_name='인허가일자')),
                ('BSN_STATE_NM', models.CharField(max_length=255, verbose_name='영업상태명')),
                ('CLSBIZ_DE', models.DateField(null=True, verbose_name='폐업일자')),
                ('LOCPLC_AR', models.FloatField(null=True, verbose_name='소재지면적(㎡)')),
                ('ENTRNC_PSN_CAPA', models.IntegerField(verbose_name='입소정원(명)')),
                ('QUALFCTN_POSESN_PSN_CNT', models.IntegerField(null=True, verbose_name='자격소유인원수(명)')),
                ('TOT_PSN_CNT', models.IntegerField(null=True, verbose_name='총인원수(명)')),
                ('REFINE_LOTNO_ADDR', models.CharField(max_length=255, verbose_name='소재지지번주소')),
                ('REFINE_ROADNM_ADDR', models.CharField(max_length=255, verbose_name='소재지도로명주소')),
                ('REFINE_ZIP_CD', models.IntegerField(verbose_name='소재지우편번호')),
                ('REFINE_WGS84_LAT', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='WGS84위도')),
                ('REFINE_WGS84_LOGT', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='WGS84경도')),
            ],
        ),
    ]
