# Generated by Django 2.2.1 on 2019-05-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='REFINE_LOTNO_ADDR',
            field=models.CharField(max_length=255, null=True, verbose_name='소재지지번주소'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='REFINE_ROADNM_ADDR',
            field=models.CharField(max_length=255, null=True, verbose_name='소재지도로명주소'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='REFINE_WGS84_LOGT',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='WGS84경도'),
        ),
    ]
