# Generated by Django 2.2.1 on 2019-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20190506_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='REFINE_WGS84_LAT',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True, verbose_name='WGS84위도'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='REFINE_WGS84_LOGT',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True, verbose_name='WGS84경도'),
        ),
    ]
