# Generated by Django 2.2.1 on 2019-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20190506_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='BSN_STATE_NM',
            field=models.CharField(max_length=255, null=True, verbose_name='영업상태명'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ENTRNC_PSN_CAPA',
            field=models.IntegerField(null=True, verbose_name='입소정원(명)'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='LICENSG_DE',
            field=models.DateField(null=True, verbose_name='인허가일자'),
        ),
    ]
